from . import hr_employee
from . import compliance_document
from . import government_transaction
from . import compliance_case
from . import eos
from . import gosi
from . import wps
from . import clearance
from . import dashboard
from . import res_config_settings
from . import government_service
from . import employee_dependent
from . import compliance_action
from . import audit
from . import wizard_bulk_reminder
from . import compliance_rule
from . import muqeem_operations
