from odoo import api, fields, models, _

class SaudiComplianceRule(models.Model):
    _name = 'saudi.compliance.rule'
    _description = 'Saudi HR Compliance Rule'
    _order = 'sequence, code'
    name = fields.Char(required=True, translate=True)
    code = fields.Char(required=True)
    category = fields.Selection([('identity', 'Identity'), ('residency', 'Residency'), ('employment', 'Employment'), ('insurance', 'Insurance'), ('gosi', 'GOSI'), ('qiwa', 'Qiwa'), ('wps', 'WPS'), ('offboarding', 'Offboarding'), ('document', 'Document'), ('process', 'Process')], required=True)
    sequence = fields.Integer(default=10)
    severity = fields.Selection([('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium')
    active = fields.Boolean(default=True)
    required_for_non_saudi = fields.Boolean(default=False)
    required_for_saudi = fields.Boolean(default=False)
    required_for_gcc = fields.Boolean(default=False)
    reminder_days = fields.Integer(default=30)
    check_key = fields.Char(required=True, help='Technical check key implemented by the compliance evaluator.')
    description = fields.Text(translate=True)
    _sql_constraints = [('rule_code_unique', 'unique(code)', 'Compliance rule code must be unique.')]

    def evaluate_employee(self, employee):
        self.ensure_one()
        key = self.check_key
        today = fields.Date.context_today(self)
        checks = {'iqama_present': bool(employee.iqama_number), 'iqama_valid': bool(employee.iqama_expiry_date and employee.iqama_expiry_date >= today), 'passport_present': bool(employee.passport_number), 'passport_valid': bool(employee.passport_expiry_date and employee.passport_expiry_date >= today), 'work_permit_present': bool(employee.work_permit_number), 'work_permit_valid': bool(employee.work_permit_expiry_date and employee.work_permit_expiry_date >= today), 'insurance_present': bool(employee.insurance_policy_number), 'insurance_valid': bool(employee.insurance_expiry_date and employee.insurance_expiry_date >= today), 'gosi_active': employee.gosi_status == 'active', 'qiwa_active': employee.qiwa_contract_status == 'active'}
        return checks.get(key, True)

class SaudiComplianceEvaluation(models.Model):
    _name = 'saudi.compliance.evaluation'
    _description = 'Saudi Employee Compliance Evaluation'
    _inherit = ['mail.thread']
    _order = 'evaluation_date desc'
    name = fields.Char(default='New', required=True)
    employee_id = fields.Many2one('hr.employee', required=True, ondelete='cascade')
    evaluation_date = fields.Datetime(default=fields.Datetime.now, required=True)
    evaluator_id = fields.Many2one('res.users', default=lambda self: self.env.user)
    overall_score = fields.Float(compute='_compute_score', store=True)
    result = fields.Selection([('pass', 'Pass'), ('warning', 'Warning'), ('fail', 'Fail')], compute='_compute_score', store=True)
    line_ids = fields.One2many('saudi.compliance.evaluation.line', 'evaluation_id')
    notes = fields.Text()

    @api.depends('line_ids.status', 'line_ids.weight')
    def _compute_score(self):
        for rec in self:
            total = sum(rec.line_ids.mapped('weight'))
            passed = sum((l.weight for l in rec.line_ids if l.status == 'pass'))
            rec.overall_score = passed / total * 100 if total else 0
            rec.result = 'pass' if rec.overall_score >= 85 else 'warning' if rec.overall_score >= 60 else 'fail'

    @api.model
    def create_for_employee(self, employee):
        rules = self.env['saudi.compliance.rule'].search([('active', '=', True)], order='sequence,code')
        evaluation = self.create({'employee_id': employee.id, 'name': _('Evaluation - %s') % employee.name})
        for rule in rules:
            required = rule.required_for_non_saudi if employee.saudi_employee_type == 'non_saudi' else rule.required_for_saudi
            if employee.saudi_employee_type == 'gulf':
                required = rule.required_for_gcc
            status = 'pass' if not required or rule.evaluate_employee(employee) else 'fail'
            self.env['saudi.compliance.evaluation.line'].create({'evaluation_id': evaluation.id, 'rule_id': rule.id, 'status': status, 'weight': {'low': 1, 'medium': 2, 'high': 4, 'critical': 8}[rule.severity], 'finding': _('Rule %s passed.') % rule.code if status == 'pass' else _('Rule %s failed.') % rule.code})
        return evaluation

class SaudiComplianceEvaluationLine(models.Model):
    _name = 'saudi.compliance.evaluation.line'
    _description = 'Compliance Evaluation Result'
    evaluation_id = fields.Many2one('saudi.compliance.evaluation', required=True, ondelete='cascade')
    rule_id = fields.Many2one('saudi.compliance.rule', required=True)
    status = fields.Selection([('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='na', required=True)
    weight = fields.Float(default=1.0)
    finding = fields.Text()
    remediation = fields.Text()
SAUDI_RULE_CATALOG = [{'code': 'KSA-001',
  'name': 'Saudi compliance control 001',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 001 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 1,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-002',
  'name': 'Saudi compliance control 002',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 002 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 2,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-003',
  'name': 'Saudi compliance control 003',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 003 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 3,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-004',
  'name': 'Saudi compliance control 004',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 004 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 4,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-005',
  'name': 'Saudi compliance control 005',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 005 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 5,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-006',
  'name': 'Saudi compliance control 006',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 006 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 6,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-007',
  'name': 'Saudi compliance control 007',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 007 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 7,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-008',
  'name': 'Saudi compliance control 008',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 008 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 8,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-009',
  'name': 'Saudi compliance control 009',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 009 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 9,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-010',
  'name': 'Saudi compliance control 010',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 010 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 10,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-011',
  'name': 'Saudi compliance control 011',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 011 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 11,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-012',
  'name': 'Saudi compliance control 012',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 012 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 12,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-013',
  'name': 'Saudi compliance control 013',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 013 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 13,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-014',
  'name': 'Saudi compliance control 014',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 014 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 14,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-015',
  'name': 'Saudi compliance control 015',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 015 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 15,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-016',
  'name': 'Saudi compliance control 016',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 016 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 16,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-017',
  'name': 'Saudi compliance control 017',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 017 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 17,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-018',
  'name': 'Saudi compliance control 018',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 018 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 18,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-019',
  'name': 'Saudi compliance control 019',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 019 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 19,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-020',
  'name': 'Saudi compliance control 020',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 020 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 20,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-021',
  'name': 'Saudi compliance control 021',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 021 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 21,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-022',
  'name': 'Saudi compliance control 022',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 022 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 22,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-023',
  'name': 'Saudi compliance control 023',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 023 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 23,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-024',
  'name': 'Saudi compliance control 024',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 024 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 24,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-025',
  'name': 'Saudi compliance control 025',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 025 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 25,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-026',
  'name': 'Saudi compliance control 026',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 026 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 26,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-027',
  'name': 'Saudi compliance control 027',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 027 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 27,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-028',
  'name': 'Saudi compliance control 028',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 028 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 28,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-029',
  'name': 'Saudi compliance control 029',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 029 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 29,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-030',
  'name': 'Saudi compliance control 030',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 030 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 30,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-031',
  'name': 'Saudi compliance control 031',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 031 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 31,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-032',
  'name': 'Saudi compliance control 032',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 032 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 32,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-033',
  'name': 'Saudi compliance control 033',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 033 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 33,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-034',
  'name': 'Saudi compliance control 034',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 034 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 34,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-035',
  'name': 'Saudi compliance control 035',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 035 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 35,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-036',
  'name': 'Saudi compliance control 036',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 036 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 36,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-037',
  'name': 'Saudi compliance control 037',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 037 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 37,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-038',
  'name': 'Saudi compliance control 038',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 038 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 38,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-039',
  'name': 'Saudi compliance control 039',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 039 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 39,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-040',
  'name': 'Saudi compliance control 040',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 040 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 40,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-041',
  'name': 'Saudi compliance control 041',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 041 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 41,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-042',
  'name': 'Saudi compliance control 042',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 042 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 42,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-043',
  'name': 'Saudi compliance control 043',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 043 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 43,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-044',
  'name': 'Saudi compliance control 044',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 044 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 44,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-045',
  'name': 'Saudi compliance control 045',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 045 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 45,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-046',
  'name': 'Saudi compliance control 046',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 046 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 46,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-047',
  'name': 'Saudi compliance control 047',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 047 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 47,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-048',
  'name': 'Saudi compliance control 048',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 048 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 48,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-049',
  'name': 'Saudi compliance control 049',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 049 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 49,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-050',
  'name': 'Saudi compliance control 050',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 050 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 50,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-051',
  'name': 'Saudi compliance control 051',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 051 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 51,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-052',
  'name': 'Saudi compliance control 052',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 052 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 52,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-053',
  'name': 'Saudi compliance control 053',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 053 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 53,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-054',
  'name': 'Saudi compliance control 054',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 054 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 54,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-055',
  'name': 'Saudi compliance control 055',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 055 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 55,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-056',
  'name': 'Saudi compliance control 056',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 056 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 56,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-057',
  'name': 'Saudi compliance control 057',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 057 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 57,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-058',
  'name': 'Saudi compliance control 058',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 058 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 58,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-059',
  'name': 'Saudi compliance control 059',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 059 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 59,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-060',
  'name': 'Saudi compliance control 060',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 060 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 60,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-061',
  'name': 'Saudi compliance control 061',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 061 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 61,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-062',
  'name': 'Saudi compliance control 062',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 062 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 62,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-063',
  'name': 'Saudi compliance control 063',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 063 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 63,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-064',
  'name': 'Saudi compliance control 064',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 064 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 64,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-065',
  'name': 'Saudi compliance control 065',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 065 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 65,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-066',
  'name': 'Saudi compliance control 066',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 066 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 66,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-067',
  'name': 'Saudi compliance control 067',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 067 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 67,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-068',
  'name': 'Saudi compliance control 068',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 068 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 68,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-069',
  'name': 'Saudi compliance control 069',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 069 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 69,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-070',
  'name': 'Saudi compliance control 070',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 070 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 70,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-071',
  'name': 'Saudi compliance control 071',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 071 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 71,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-072',
  'name': 'Saudi compliance control 072',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 072 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 72,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-073',
  'name': 'Saudi compliance control 073',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 073 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 73,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-074',
  'name': 'Saudi compliance control 074',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 074 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 74,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-075',
  'name': 'Saudi compliance control 075',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 075 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 75,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-076',
  'name': 'Saudi compliance control 076',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 076 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 76,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-077',
  'name': 'Saudi compliance control 077',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 077 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 77,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-078',
  'name': 'Saudi compliance control 078',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 078 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 78,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-079',
  'name': 'Saudi compliance control 079',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 079 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 79,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-080',
  'name': 'Saudi compliance control 080',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 080 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 80,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-081',
  'name': 'Saudi compliance control 081',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 081 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 81,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-082',
  'name': 'Saudi compliance control 082',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 082 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 82,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-083',
  'name': 'Saudi compliance control 083',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 083 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 83,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-084',
  'name': 'Saudi compliance control 084',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 084 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 84,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-085',
  'name': 'Saudi compliance control 085',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 085 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 85,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-086',
  'name': 'Saudi compliance control 086',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 086 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 86,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-087',
  'name': 'Saudi compliance control 087',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 087 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 87,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-088',
  'name': 'Saudi compliance control 088',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 088 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 88,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-089',
  'name': 'Saudi compliance control 089',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 089 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 89,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-090',
  'name': 'Saudi compliance control 090',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 090 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 90,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-091',
  'name': 'Saudi compliance control 091',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 091 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 91,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-092',
  'name': 'Saudi compliance control 092',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 092 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 92,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-093',
  'name': 'Saudi compliance control 093',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 093 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 93,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-094',
  'name': 'Saudi compliance control 094',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 094 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 94,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-095',
  'name': 'Saudi compliance control 095',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 095 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 95,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-096',
  'name': 'Saudi compliance control 096',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 096 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 96,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-097',
  'name': 'Saudi compliance control 097',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 097 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 97,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-098',
  'name': 'Saudi compliance control 098',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 098 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 98,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-099',
  'name': 'Saudi compliance control 099',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 099 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 99,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-100',
  'name': 'Saudi compliance control 100',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 100 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 100,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-101',
  'name': 'Saudi compliance control 101',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 101 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 101,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-102',
  'name': 'Saudi compliance control 102',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 102 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 102,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-103',
  'name': 'Saudi compliance control 103',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 103 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 103,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-104',
  'name': 'Saudi compliance control 104',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 104 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 104,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-105',
  'name': 'Saudi compliance control 105',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 105 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 105,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-106',
  'name': 'Saudi compliance control 106',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 106 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 106,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-107',
  'name': 'Saudi compliance control 107',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 107 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 107,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-108',
  'name': 'Saudi compliance control 108',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 108 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 108,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-109',
  'name': 'Saudi compliance control 109',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 109 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 109,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-110',
  'name': 'Saudi compliance control 110',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 110 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 110,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-111',
  'name': 'Saudi compliance control 111',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 111 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 111,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-112',
  'name': 'Saudi compliance control 112',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 112 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 112,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-113',
  'name': 'Saudi compliance control 113',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 113 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 113,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-114',
  'name': 'Saudi compliance control 114',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 114 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 114,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-115',
  'name': 'Saudi compliance control 115',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 115 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 115,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-116',
  'name': 'Saudi compliance control 116',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 116 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 116,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-117',
  'name': 'Saudi compliance control 117',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 117 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 117,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-118',
  'name': 'Saudi compliance control 118',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 118 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 118,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-119',
  'name': 'Saudi compliance control 119',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 119 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 119,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-120',
  'name': 'Saudi compliance control 120',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 120 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 120,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-121',
  'name': 'Saudi compliance control 121',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 121 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 121,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-122',
  'name': 'Saudi compliance control 122',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 122 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 122,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-123',
  'name': 'Saudi compliance control 123',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 123 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 123,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-124',
  'name': 'Saudi compliance control 124',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 124 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 124,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-125',
  'name': 'Saudi compliance control 125',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 125 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 125,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-126',
  'name': 'Saudi compliance control 126',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 126 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 126,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-127',
  'name': 'Saudi compliance control 127',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 127 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 127,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-128',
  'name': 'Saudi compliance control 128',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 128 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 128,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-129',
  'name': 'Saudi compliance control 129',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 129 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 129,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-130',
  'name': 'Saudi compliance control 130',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 130 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 130,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-131',
  'name': 'Saudi compliance control 131',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 131 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 131,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-132',
  'name': 'Saudi compliance control 132',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 132 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 132,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-133',
  'name': 'Saudi compliance control 133',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 133 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 133,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-134',
  'name': 'Saudi compliance control 134',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 134 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 134,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-135',
  'name': 'Saudi compliance control 135',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 135 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 135,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-136',
  'name': 'Saudi compliance control 136',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 136 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 136,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-137',
  'name': 'Saudi compliance control 137',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 137 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 137,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-138',
  'name': 'Saudi compliance control 138',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 138 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 138,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-139',
  'name': 'Saudi compliance control 139',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 139 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 139,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-140',
  'name': 'Saudi compliance control 140',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 140 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 140,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-141',
  'name': 'Saudi compliance control 141',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 141 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 141,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-142',
  'name': 'Saudi compliance control 142',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 142 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 142,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-143',
  'name': 'Saudi compliance control 143',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 143 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 143,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-144',
  'name': 'Saudi compliance control 144',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 144 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 144,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-145',
  'name': 'Saudi compliance control 145',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 145 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 145,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-146',
  'name': 'Saudi compliance control 146',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 146 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 146,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-147',
  'name': 'Saudi compliance control 147',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 147 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 147,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-148',
  'name': 'Saudi compliance control 148',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 148 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 148,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-149',
  'name': 'Saudi compliance control 149',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 149 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 149,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-150',
  'name': 'Saudi compliance control 150',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 150 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 150,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-151',
  'name': 'Saudi compliance control 151',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 151 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 151,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-152',
  'name': 'Saudi compliance control 152',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 152 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 152,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-153',
  'name': 'Saudi compliance control 153',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 153 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 153,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-154',
  'name': 'Saudi compliance control 154',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 154 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 154,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-155',
  'name': 'Saudi compliance control 155',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 155 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 155,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-156',
  'name': 'Saudi compliance control 156',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 156 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 156,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-157',
  'name': 'Saudi compliance control 157',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 157 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 157,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-158',
  'name': 'Saudi compliance control 158',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 158 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 158,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-159',
  'name': 'Saudi compliance control 159',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 159 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 159,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-160',
  'name': 'Saudi compliance control 160',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 160 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 160,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-161',
  'name': 'Saudi compliance control 161',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 161 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 161,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-162',
  'name': 'Saudi compliance control 162',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 162 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 162,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-163',
  'name': 'Saudi compliance control 163',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 163 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 163,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-164',
  'name': 'Saudi compliance control 164',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 164 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 164,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-165',
  'name': 'Saudi compliance control 165',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 165 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 165,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-166',
  'name': 'Saudi compliance control 166',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 166 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 166,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-167',
  'name': 'Saudi compliance control 167',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 167 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 167,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-168',
  'name': 'Saudi compliance control 168',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 168 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 168,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-169',
  'name': 'Saudi compliance control 169',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 169 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 169,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-170',
  'name': 'Saudi compliance control 170',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 170 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 170,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-171',
  'name': 'Saudi compliance control 171',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 171 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 171,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-172',
  'name': 'Saudi compliance control 172',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 172 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 172,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-173',
  'name': 'Saudi compliance control 173',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 173 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 173,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-174',
  'name': 'Saudi compliance control 174',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 174 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 174,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-175',
  'name': 'Saudi compliance control 175',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 175 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 175,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-176',
  'name': 'Saudi compliance control 176',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 176 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 176,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-177',
  'name': 'Saudi compliance control 177',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 177 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 177,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-178',
  'name': 'Saudi compliance control 178',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 178 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 178,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-179',
  'name': 'Saudi compliance control 179',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 179 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 179,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-180',
  'name': 'Saudi compliance control 180',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 180 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 180,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-181',
  'name': 'Saudi compliance control 181',
  'category': 'identity',
  'severity': 'low',
  'check_key': 'iqama_present',
  'description': 'Operational control 181 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 181,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-182',
  'name': 'Saudi compliance control 182',
  'category': 'residency',
  'severity': 'medium',
  'check_key': 'iqama_valid',
  'description': 'Operational control 182 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 182,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-183',
  'name': 'Saudi compliance control 183',
  'category': 'employment',
  'severity': 'high',
  'check_key': 'passport_present',
  'description': 'Operational control 183 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 183,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-184',
  'name': 'Saudi compliance control 184',
  'category': 'insurance',
  'severity': 'critical',
  'check_key': 'passport_valid',
  'description': 'Operational control 184 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 184,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-185',
  'name': 'Saudi compliance control 185',
  'category': 'gosi',
  'severity': 'low',
  'check_key': 'work_permit_present',
  'description': 'Operational control 185 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 185,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-186',
  'name': 'Saudi compliance control 186',
  'category': 'qiwa',
  'severity': 'medium',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 186 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 186,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-187',
  'name': 'Saudi compliance control 187',
  'category': 'wps',
  'severity': 'high',
  'check_key': 'insurance_present',
  'description': 'Operational control 187 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 187,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-188',
  'name': 'Saudi compliance control 188',
  'category': 'offboarding',
  'severity': 'critical',
  'check_key': 'insurance_valid',
  'description': 'Operational control 188 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 188,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-189',
  'name': 'Saudi compliance control 189',
  'category': 'document',
  'severity': 'low',
  'check_key': 'gosi_active',
  'description': 'Operational control 189 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 189,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-190',
  'name': 'Saudi compliance control 190',
  'category': 'process',
  'severity': 'medium',
  'check_key': 'qiwa_active',
  'description': 'Operational control 190 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 190,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-191',
  'name': 'Saudi compliance control 191',
  'category': 'identity',
  'severity': 'high',
  'check_key': 'iqama_present',
  'description': 'Operational control 191 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 191,
  'required_for_non_saudi': False,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 15},
 {'code': 'KSA-192',
  'name': 'Saudi compliance control 192',
  'category': 'residency',
  'severity': 'critical',
  'check_key': 'iqama_valid',
  'description': 'Operational control 192 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 192,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-193',
  'name': 'Saudi compliance control 193',
  'category': 'employment',
  'severity': 'low',
  'check_key': 'passport_present',
  'description': 'Operational control 193 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 193,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': True,
  'reminder_days': 30},
 {'code': 'KSA-194',
  'name': 'Saudi compliance control 194',
  'category': 'insurance',
  'severity': 'medium',
  'check_key': 'passport_valid',
  'description': 'Operational control 194 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 194,
  'required_for_non_saudi': True,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-195',
  'name': 'Saudi compliance control 195',
  'category': 'gosi',
  'severity': 'high',
  'check_key': 'work_permit_present',
  'description': 'Operational control 195 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 195,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-196',
  'name': 'Saudi compliance control 196',
  'category': 'qiwa',
  'severity': 'critical',
  'check_key': 'work_permit_valid',
  'description': 'Operational control 196 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 196,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-197',
  'name': 'Saudi compliance control 197',
  'category': 'wps',
  'severity': 'low',
  'check_key': 'insurance_present',
  'description': 'Operational control 197 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 197,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-198',
  'name': 'Saudi compliance control 198',
  'category': 'offboarding',
  'severity': 'medium',
  'check_key': 'insurance_valid',
  'description': 'Operational control 198 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 198,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 30},
 {'code': 'KSA-199',
  'name': 'Saudi compliance control 199',
  'category': 'document',
  'severity': 'high',
  'check_key': 'gosi_active',
  'description': 'Operational control 199 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 199,
  'required_for_non_saudi': True,
  'required_for_saudi': True,
  'required_for_gcc': False,
  'reminder_days': 15},
 {'code': 'KSA-200',
  'name': 'Saudi compliance control 200',
  'category': 'process',
  'severity': 'critical',
  'check_key': 'qiwa_active',
  'description': 'Operational control 200 for Saudi HR government compliance. Validate the '
                 'required record, supporting evidence, owner and remediation timeline.',
  'sequence': 200,
  'required_for_non_saudi': False,
  'required_for_saudi': False,
  'required_for_gcc': False,
  'reminder_days': 15}]
