{'name': 'Advanced Last-Mile & Own-Fleet Delivery Manager Pro', 'version': '17.0.1.0.0',
 'category': 'Inventory / Supply Chain',
 'summary': 'Complete own-fleet last-mile delivery system with route planning, optimization, driver/vehicle assignment, proof of delivery, status tracking and profitability analysis.',
 'description': 'Professional delivery management for companies using their own fleet.\nCovers route planning, optimization, dispatch, driver and vehicle assignment, proof of delivery,\nfailed delivery handling, customer tracking, route costing and operational analytics.',
 'author': 'Custom Development', 'license': 'LGPL-3',
 'depends': ['base', 'stock', 'sale_management', 'fleet', 'hr', 'mail', 'web', 'account', 'portal'],
 'data': ['security/security.xml', 'security/ir.model.access.csv', 'data/delivery_route_data.xml',
          'data/delivery_extra_data.xml', 'data/mail_template_data.xml', 'data/delivery_cron.xml',
          'views/delivery_route_views.xml', 'views/delivery_advanced_views.xml', 'views/delivery_master_views.xml',
          'views/advanced_views.xml', 'views/geocode_audit_views.xml', 'views/retry_views.xml',
          'views/portal_templates.xml', 'views/portal_extra_templates.xml', 'views/delivery_proof_views.xml',
          'views/stock_picking_views.xml', 'views/res_partner_views.xml', 'views/fleet_vehicle_views.xml',
          'views/hr_employee_views.xml', 'views/wizards_views.xml', 'views/dashboard_views.xml',
          'views/route_operational_views.xml', 'views/search_views.xml', 'views/kpi_extra_views.xml',
          'views/wizard_extra_views.xml', 'views/res_config_settings_views.xml', 'views/menus.xml',
          'views/advanced_menus.xml', 'report/delivery_pod_report.xml', 'report/delivery_advanced_reports.xml'],
 'assets': {'web.assets_frontend': ['delivery_fleet_pro/static/src/css/delivery_portal.css',
                                    'delivery_fleet_pro/static/src/js/delivery_tracking.js'],
            'web.assets_backend': ['delivery_fleet_pro/static/src/css/delivery_dashboard.css',
                                   'delivery_fleet_pro/static/src/js/delivery_dashboard.js',
                                   'delivery_fleet_pro/static/src/xml/delivery_dashboard.xml']}, 'installable': True,
 'application': True}
