from . import delivery_config
from . import delivery_service
from . import delivery_sla
from . import delivery_route_template
from . import res_partner
from . import delivery_route
from . import delivery_route_line
from . import delivery_proof
from . import delivery_failure
from . import delivery_attempt
from . import delivery_retry
from . import delivery_package
from . import delivery_segment
from . import delivery_charge
from . import delivery_cost
from . import delivery_event
from . import delivery_tracking
from . import delivery_geocode
from . import delivery_vehicle_log
from . import delivery_driver_schedule
from . import delivery_notification
from . import delivery_notification_service
from . import delivery_pricing
from . import fleet_vehicle
from . import hr_employee
from . import delivery_capacity
from . import delivery_scheduler
from . import delivery_routing_service
from . import delivery_validators
from . import delivery_audit
from . import stock_picking
from . import res_config_settings
# Extensions are imported only after every base model they inherit from exists.
from . import delivery_advanced
# Reporting models are deliberately imported last.
from . import delivery_kpi_snapshot
from . import delivery_kpi_engine
from . import delivery_driver_performance
from . import delivery_metric
